### ISSUE TITLE
ошибка при передаче заказа в офд

### ISSUE THREAD

**Issue by dmitgor** [mediaceh/ferma-ofd-wordpress#1]
Добрый день.
После установки плагина и настройки попытался провести первый заказ и получаю ошибку
ОШИБКА ОФД: Некорректный формат запроса (скриншот прилагаю)

Прошу помочь, потому что техподдержка ofd.ru помочь не может.
Что надо сделать, чтобы плагин заработал?

![2020-08-19_12-12-30](https://user-images.githubusercontent.com/69891810/90603816-4ea75080-e215-11ea-8efd-595b0d2930e3.png)

**Comment by mediaceh** [comment]
Добрый. Это ответ от их сервера. Из вашего скриншота непонятно какие вы совершаете действия и на каком этапе приходит данный ответ. Так же вы не указали версии используемых программ.

**Comment by dmitgor** [comment]
Благодарю за ответ.
Проблема возникала при попытке фискализации чека: при переводе заказа в статус для отправки данных в ОФД, либо при попытке ручного формирования любого чека (прихода или возврата).

Эту проблему в итоге решил, убрав чекбокс в настройках "Принудительная свертка позиций заказа".

**Comment by mediaceh** [comment]
Спасибо за фидбек. Может быть кому то поможет.
